steps:
  # Step 1: Build the Docker image from the root Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sliceai-backend:$COMMIT_SHA'
      - '.'

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sliceai-backend:$COMMIT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sliceai-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sliceai-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/sliceai-backend:$COMMIT_SHA'

# Required when a service account is configured on the trigger
options:
  logging: CLOUD_LOGGING_ONLY
